trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '23.x'
  displayName: 'Install Node.js'

- script: |
    cd frontend
    npm install
    npm run build
  displayName: 'Build Frontend'

- task: Docker@2
  inputs:
    command: 'build'
    repository: 'evertonst/chatevt-frontend'
    dockerfile: '$(Build.SourcesDirectory)/frontend/Dockerfile'
    tags: 'latest'
  displayName: 'Build Frontend Docker Image'

- task: Docker@2
  inputs:
    command: 'build'
    repository: 'evertonst/chatevt-backend'
    dockerfile: '$(Build.SourcesDirectory)/backend/Dockerfile'
    tags: 'latest'
  displayName: 'Build Backend Docker Image'

- task: Docker@2
  inputs:
    command: 'push'
    repository: 'evertonst/chatevt-frontend'
    tags: 'latest'
    containerRegistry: 'dockerHubConnection'
  displayName: 'Push Frontend Docker Image'

- task: Docker@2
  inputs:
    command: 'push'
    repository: 'evertonst/chatevt-backend'
    tags: 'latest'
    containerRegistry: 'dockerHubConnection'
  displayName: 'Push Backend Docker Image'