version: '3.8'
services:
  frontend:
    image: evertonst/chatevt-frontend:latest
    ports:
      - "3000:3000"
  backend:
    image: evertonst/chatevt-backend:latest
    ports:
      - "5000:5000"
    environment:
      - TOKEN=${TOKEN}